import './globals.css'
import { Inter } from 'next/font/google'
import Menu from './components/menu.jsx'
import Home from './components/home.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Autonimate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </>
  )
}
